name: RecipeRemover
description: Remove vanilla recipes from the server
version: ${project.version}
website: http://robomwm.com
author: RoboMWM
main: com.robomwm.reciperemover.RecipeRemover
loadbefore: [CustomItemRecipes, Slimefun]
softdepend: [Multiverse-Core]
